model_list:
  - model_name: google/gemini-2.5-pro-preview
    litellm_params: 
      model: openrouter/google/gemini-2.5-pro-preview
      api_key: "os.environ/OPENROUTER_API_KEY"
      web_search_options: {}
    model_info:
      max_input_tokens: 1048576
      max_output_tokens: 65535
      input_cost_per_token: 0.00000125
      output_cost_per_token: 0.00001
      supports_vision: true
      supports_web_search: true
      supports_function_calling: true
      supports_assistant_prefill: true
      supports_computer_use: false
  - model_name: google/gemini-2.5-pro-preview-online
    litellm_params: 
      model: openrouter/google/gemini-2.5-pro-preview:online
      api_key: "os.environ/OPENROUTER_API_KEY"
      web_search_options: {}
    model_info:
      max_input_tokens: 1048576
      max_output_tokens: 65535
      input_cost_per_token: 0.00000125
      output_cost_per_token: 0.00001
      supports_vision: true
      supports_web_search: true
      supports_function_calling: true
      supports_assistant_prefill: true
      supports_computer_use: false
  - model_name: anthropic/claude-sonnet-4
    litellm_params: 
      model: openrouter/anthropic/claude-sonnet-4
      api_key: "os.environ/OPENROUTER_API_KEY"
      web_search_options: {}
    model_info:
      max_input_tokens: 200000
      max_output_tokens: 8192
      input_cost_per_token: 0.000003
      output_cost_per_token: 0.000015
      supports_vision: true
      supports_web_search: true
      supports_prompt_caching: true
      cache_read_input_token_cost: 0.0000003
      cache_creation_input_token_cost: 0.00000375
      supports_function_calling: true
      supports_assistant_prefill: true
      supports_computer_use: false
  - model_name: anthropic/claude-sonnet-4-online
    litellm_params: 
      model: openrouter/anthropic/claude-sonnet-4:online
      api_key: "os.environ/OPENROUTER_API_KEY"
      web_search_options: {}
    model_info:
      max_input_tokens: 200000
      max_output_tokens: 8192
      input_cost_per_token: 0.000003
      output_cost_per_token: 0.000015
      supports_vision: true
      supports_web_search: true
      supports_prompt_caching: true
      cache_read_input_token_cost: 0.0000003
      cache_creation_input_token_cost: 0.00000375
      supports_function_calling: true
      supports_assistant_prefill: true
      supports_computer_use: false
  # - model_name: model_name
  #   litellm_params: 
  #     thinking: { "type": "enabled", "budget_tokens": 2048 }
  #     merge_reasoning_content_in_choices: true
  #     drop_params: true
  #     additional_drop_params: ["reasoning_effort", "thinking"]
  #   model_info:
  #     supports_reasoning: true