services:
  litellm-db:
    image: postgres:16
    restart: always
    container_name: litellm-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - litellm-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - litellm-network
  litellm:
    build:
      context: .
      dockerfile: Dockerfile
    image: litellm
    container_name: litellm
    environment:
      LITELLM_MASTER_KEY: ${LITELLM_MASTER_KEY}
      LITELLM_SALT_KEY: ${LITELLM_SALT_KEY}
      UI_USERNAME: ${UI_USERNAME}
      UI_PASSWORD: ${UI_PASSWORD}
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@litellm-db:5432/${POSTGRES_DB}"
      STORE_MODEL_IN_DB: "True"
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      http_proxy: ""
      https_proxy: ""
    depends_on:
      - litellm-db
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 http://localhost:4000/health/liveliness || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - litellm-network

volumes:
  litellm-db:
    name: litellm-db

networks:
  litellm-network:
    name: litellm-network
    driver: bridge