model_list:
  - model_name: anthropic/claude-sonnet-4.5
    litellm_params: 
      model: openrouter/anthropic/claude-sonnet-4.5
      api_key: "os.environ/OPENROUTER_API_KEY"
      web_search_options: {}
    model_info:
      max_input_tokens: 1000000
      max_output_tokens: 64000
      input_cost_per_token: 0.000003
      output_cost_per_token: 0.000015
      supports_vision: true
      supports_web_search: true
      supports_prompt_caching: true
      cache_read_input_token_cost: 0.0000003
      cache_creation_input_token_cost: 0.00000375
      supports_function_calling: true
      supports_assistant_prefill: true
      supports_computer_use: false
  - model_name: anthropic/claude-sonnet-4.5-online
    litellm_params: 
      model: openrouter/anthropic/claude-sonnet-4.5:online
      api_key: "os.environ/OPENROUTER_API_KEY"
      web_search_options: {}
    model_info:
      max_input_tokens: 1000000
      max_output_tokens: 64000
      input_cost_per_token: 0.000003
      output_cost_per_token: 0.000015
      supports_vision: true
      supports_web_search: true
      supports_prompt_caching: true
      cache_read_input_token_cost: 0.0000003
      cache_creation_input_token_cost: 0.00000375
      supports_function_calling: true
      supports_assistant_prefill: true
      supports_computer_use: false