model_list:
  - model_name: deepseek/deepseek-v3.2-exp
    litellm_params: 
      model: openrouter/deepseek/deepseek-v3.2-exp:exacto:nitro
      api_key: "os.environ/OPENROUTER_API_KEY"
      web_search_options: {}
    model_info:
      max_input_tokens: 163840
      max_output_tokens: 64000
      input_cost_per_token: 0.00000027
      output_cost_per_token: 0.0000004
      supports_vision: true
      supports_web_search: true
      supports_prompt_caching: true
      cache_read_input_token_cost: 0
      cache_creation_input_token_cost: 0
      supports_function_calling: true
      supports_assistant_prefill: true
      supports_computer_use: false
  - model_name: deepseek/deepseek-v3.2-exp-online
    litellm_params: 
      model: openrouter/deepseek/deepseek-v3.2-exp:online:exacto:nitro
      api_key: "os.environ/OPENROUTER_API_KEY"
      web_search_options: {}
    model_info:
      max_input_tokens: 163840
      max_output_tokens: 64000
      input_cost_per_token: 0.00000027
      output_cost_per_token: 0.0000004
      supports_vision: true
      supports_web_search: true
      supports_prompt_caching: true
      cache_read_input_token_cost: 0
      cache_creation_input_token_cost: 0
      supports_function_calling: true
      supports_assistant_prefill: true
      supports_computer_use: false