model_list:
  - model_name: google/gemini-2.5-pro
    litellm_params: 
      model: openrouter/google/gemini-2.5-pro:nitro
      api_key: "os.environ/OPENROUTER_API_KEY"
      web_search_options: {}
    model_info:
      max_input_tokens: 1048576
      max_output_tokens: 65535
      input_cost_per_token: 0.00000125
      output_cost_per_token: 0.00001
      supports_vision: true
      supports_web_search: true
      supports_prompt_caching: true
      cache_read_input_token_cost: 0.000000125
      cache_creation_input_token_cost: 0.000001625
      supports_function_calling: true
      supports_assistant_prefill: true
      supports_computer_use: false
  - model_name: google/gemini-2.5-pro-online
    litellm_params: 
      model: openrouter/google/gemini-2.5-pro:online:nitro
      api_key: "os.environ/OPENROUTER_API_KEY"
      web_search_options: {}
    model_info:
      max_input_tokens: 1048576
      max_output_tokens: 65535
      input_cost_per_token: 0.00000125
      output_cost_per_token: 0.00001
      supports_vision: true
      supports_web_search: true
      supports_prompt_caching: true
      cache_read_input_token_cost: 0.000000125
      cache_creation_input_token_cost: 0.000001625
      supports_function_calling: true
      supports_assistant_prefill: true
      supports_computer_use: false