model_list:
  - model_name: z-ai/glm-4.6
    litellm_params: 
      model: openrouter/z-ai/glm-4.6:exacto:nitro
      api_key: "os.environ/OPENROUTER_API_KEY"
      web_search_options: {}
    model_info:
      max_input_tokens: 200000
      max_output_tokens: 128000
      input_cost_per_token: 0.0000006
      output_cost_per_token: 0.0000022
      supports_vision: true
      supports_web_search: true
      supports_prompt_caching: true
      cache_read_input_token_cost: 0.00000011
      cache_creation_input_token_cost: 0
      supports_function_calling: true
      supports_assistant_prefill: true
      supports_computer_use: false
  - model_name: z-ai/glm-4.6-online
    litellm_params: 
      model: openrouter/z-ai/glm-4.6:online:exacto:nitro
      api_key: "os.environ/OPENROUTER_API_KEY"
      web_search_options: {}
    model_info:
      max_input_tokens: 200000
      max_output_tokens: 128000
      input_cost_per_token: 0.0000006
      output_cost_per_token: 0.0000022
      supports_vision: true
      supports_web_search: true
      supports_prompt_caching: true
      cache_read_input_token_cost: 0.00000011
      cache_creation_input_token_cost: 0
      supports_function_calling: true
      supports_assistant_prefill: true
      supports_computer_use: false