model_list:
  - model_name: openai/gpt-5
    litellm_params: 
      model: openrouter/openai/gpt-5:nitro
      api_key: "os.environ/OPENROUTER_API_KEY"
      web_search_options: {}
    model_info:
      max_input_tokens: 400000
      max_output_tokens: 128000
      input_cost_per_token: 0.00000125
      output_cost_per_token: 0.00001
      supports_vision: true
      supports_web_search: true
      supports_prompt_caching: true
      cache_read_input_token_cost: 0.000000125
      cache_creation_input_token_cost: 0
      supports_function_calling: true
      supports_assistant_prefill: true
      supports_computer_use: false
  - model_name: openai/gpt-5-online
    litellm_params: 
      model: openrouter/openai/gpt-5:online:nitro
      api_key: "os.environ/OPENROUTER_API_KEY"
      web_search_options: {}
    model_info:
      max_input_tokens: 400000
      max_output_tokens: 128000
      input_cost_per_token: 0.00000125
      output_cost_per_token: 0.00001
      supports_vision: true
      supports_web_search: true
      supports_prompt_caching: true
      cache_read_input_token_cost: 0.000000125
      cache_creation_input_token_cost: 0
      supports_function_calling: true
      supports_assistant_prefill: true
      supports_computer_use: false