model_list:
  - model_name: x-ai/grok-code-fast-1
    litellm_params: 
      model: openrouter/x-ai/grok-code-fast-1
      api_key: "os.environ/OPENROUTER_API_KEY"
      web_search_options: {}
    model_info:
      max_input_tokens: 256000
      max_output_tokens: 10000
      input_cost_per_token: 0.0000002
      output_cost_per_token: 0.0000015
      supports_vision: true
      supports_web_search: true
      supports_prompt_caching: true
      cache_read_input_token_cost: 0.00000002
      cache_creation_input_token_cost: 0.0000015
      supports_function_calling: true
      supports_assistant_prefill: true
      supports_computer_use: false
  - model_name: x-ai/grok-code-fast-1-online
    litellm_params: 
      model: openrouter/x-ai/grok-code-fast-1:online
      api_key: "os.environ/OPENROUTER_API_KEY"
      web_search_options: {}
    model_info:
      max_input_tokens: 256000
      max_output_tokens: 10000
      input_cost_per_token: 0.0000002
      output_cost_per_token: 0.0000015
      supports_vision: true
      supports_web_search: true
      supports_prompt_caching: true
      cache_read_input_token_cost: 0.00000002
      cache_creation_input_token_cost: 0.0000015
      supports_function_calling: true
      supports_assistant_prefill: true
      supports_computer_use: false